volumes:
  qts_db_data:

services:

  postgres:
    image: postgres:15-alpine
    container_name: qts-db
    volumes:
      - qts_db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$${DB_PASSWORD} pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 10

  backend:
    container_name: qts-back
    build: .
    command: >
      sh -c "
      alembic upgrade head &&
      python -m bot.main
      "
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "1"
